version: 2.1
jobs:

  semgrep-scan:
    parameters:
      repo_path:
        type: string
        default: myorg/semgrep-test-repo
      default_branch:
        type: string
        default: circleci-project-setup
    environment:
      # Scan with rules set in Semgrep App's rule board.
      # Get your token at semgrep.dev/orgs/-/settings/tokens
      SEMGREP_APP_TOKEN: 71ee4a24dbf9bfd626f413dcf242d347649010937bd9acb5a72e0dda799e8f8c

      # Scan changed files in PRs, only report new findings (existing findings ignored)
      SEMGREP_BASELINE_REF: << parameters.default_branch >>

    # == Optional settings in the `environment:` block

    # Instead of `SEMGREP_APP_TOKEN:`, set hard-coded rulesets, 
    # viewable in logs.
    #   SEMGREP_RULES: p/default # See more at semgrep.dev/explore.
    #   SEMGREP_REPO_NAME: << parameters.repo_path >>
    #   SEMGREP_REPO_URL: << pipeline.project.git_url >>
    #   SEMGREP_BRANCH: << pipeline.git.branch >>

    # Never fail the build due to findings.
    # Instead, just collect findings for semgrep.dev/manage/findings
    #   SEMGREP_AUDIT_ON: unknown

    # Change job timeout (default is 1800 seconds; set to 0 to disable)
    #   SEMGREP_TIMEOUT: 300




    docker:
      - image: returntocorp/semgrep
    steps:
      - checkout
      - run:
          name: "Semgrep scan"
          command: semgrep ci
  
  
  sonarbuild:
    docker:
      - image: 'node:latest'
    steps:
      - checkout
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.1
  
workflows:
  main:
    jobs:
      - semgrep-scan
      
      - sonarbuild




#ref: https://semgrep.dev/docs/semgrep-ci/sample-ci-configs/
