# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  semgrep: appfolio/semgrep@0.0.1
workflows:
    example-workflow:
      jobs:
        - semgrep/scan:
            repo_path: https://github.com/landtcloud/trycircleci 